apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
spec:
  securityContext:
   fsGroup: 0
  volumes:
   - name: data-volume
     hostPath:
      path: /tmp/data
   - name: persistent-volume
     persistentVolumeClaim:
      claimName: nginx-pvc
  containers:
   - name: nginx
     image: nginx
     securityContext:
       privileged: true
     ports:
       - containerPort: 80
       - containerPort: 8080
     volumeMounts:
      - name: data-volume
        mountPath: /usr/share/nginx/html/data
      - name: PersistentVolumeclaim
         mountPath: /usr/share/nginx/html/persistent
     env:
       - name: ALLOW_ANONYMOUS_LOGIN
         value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
